//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesImpresion
    {
        public int IdDetalle { get; set; }
        public int IdTamanoHoja { get; set; }
        public int IdTipoLetra { get; set; }
        public int IdTamanoLetra { get; set; }
        public byte[] ImagenFondo { get; set; }
    
        public virtual TamanoHoja TamanoHoja { get; set; }
        public virtual TamanoLetra TamanoLetra { get; set; }
        public virtual TipoLetra TipoLetra { get; set; }
    }
}
